### ISSUE TITLE
Deploy workloads on a k8s cluster with a private control plane

### ISSUE THREAD

**Issue by DanielMSchmidt** [DanielMSchmidt/cdktf-cdk8s#2]
RE: https://twitter.com/nicolai86/status/1481695327220469762

Would be cool to extend the use case to also deploy workloads on private control planes. One would probably need to schedule Something with access to the cluster control planes and apply directly what cdk8s synthesises within a provision or as a lambda workload.

**Comment by nicolai86** [comment]
See https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.Cluster.html
To create a private EKS cluster with CDK, use 

```
const cluster = new eks.Cluster(this, 'hello-eks', {
  version: eks.KubernetesVersion.V1_21,
  endpointAccess: EndpointAccess.PRIVATE
});
```

vanilla CDK can still deploy to that k8s cluster because it uses a lambda function that's deployed into the cluster VPC. how does this work with cdktf ?

**Comment by DanielMSchmidt** [comment]
Nice, thanks for link and explanation. 

> how does this work with cdktf ?

cdktf runs locally but you can provision a one time lambda or sth else with a provisioner that can apply the manifests from the inside. At least I'd assume this 🤔

**Comment by nicolai86** [comment]
A working example would be great because I have the same challenge with terraform. 😅
